Feature/hood maintainer
Team488/TeamXbot2020 pull request #38
Opened 2020-02-22 18:24 UTC by wonton-ly

2020-02-22 18:55 UTC, aschokking commented on src/main/java/competition/subsystems/hood/HoodSubsystem.java
> +    double goalAngle;
you might want these to be DoubleProperty s instead so you can debug what's going on more easily?

2020-02-22 18:55 UTC, aschokking commented on src/main/java/competition/subsystems/hood/HoodSubsystem.java
> +    private double calibrationOffset;
seems like this should be a persistent double property so we can easily tweak it without redeploying?

2020-02-22 18:55 UTC, aschokking commented on src/main/java/competition/subsystems/hood/HoodSubsystem.java
> +    public void uncalibrate(){
what would call this?

2020-02-22 20:16 UTC, JohnGilb requested changes
Let's change the hood to use a 0 to 1 system for "how extended it is" instead of using precise angle for now.

2020-02-22 20:16 UTC, JohnGilb commented on src/main/java/competition/subsystems/hood/HoodSubsystem.java
> +        goalAngleProp.set(angle);;
this definitely won't compile - you have two `;`;

2020-02-22 20:16 UTC, JohnGilb commented on src/main/java/competition/subsystems/hood/commands/HoodMaintainerCommand.java
> +        decider = clf.createHumanVsMachineDecider(this.getPrefix());
I don't think you need the decider here.

2020-02-23 18:57 UTC, JohnGilb approved these changes

2020-02-23 19:01 UTC, merged