Remade whole original "initial_position"
Team488/TeamXbot2020 pull request #61
Opened 2020-02-28 06:59 UTC by ivanthcih

Originally from Vincent's original branch, due to the amount of commits (a huge mess), was made to reset and make it more cleaner.

DESC:
Communicate the initial position to the Vision System when the match starts

2020-02-29 03:01 UTC, JohnGilb requested changes
Tests!

2020-02-29 03:01 UTC, JohnGilb commented on src/main/java/competition/subsystems/pose/PoseSubsystem.java
> +    public final DoubleProperty intPosX;
we don't use these, so we can get rid of these three properties.

2020-02-29 03:01 UTC, JohnGilb commented on src/main/java/competition/subsystems/vision/commands/SendInitialPos.java
> +public class SendInitialPos extends BaseCommand{
`SendInitialPositionToRaspberryCommand`

2020-02-29 03:01 UTC, JohnGilb commented on src/main/java/competition/subsystems/vision/commands/SendInitialPos.java
> +
Where is your constructor?

2020-03-01 05:39 UTC, JohnGilb submitted a review, later dismissed

2020-03-01 05:39 UTC, JohnGilb commented on src/test/java/competition/subsystems/vision/SendInitialPositionToRaspberryCommandTest.java
> +
This whole class doesn't actually test the Command - just the Subsystem.

2020-03-04 05:14 UTC, stephenjust approved these changes

2020-03-04 05:14 UTC, merged